"""Render the primary-source research dossier. Requires mistune; no network or LLM calls."""
from pathlib import Path
import json
import re
import base64
import html
import mistune

HERE=Path(__file__).resolve().parent
PAPER=HERE.parent
# Metadata records use abbreviated author lists where the bibliography is long.
# They are a reading list, not a claim that full BibTeX metadata was exported.
RAW='''rest|A Framework for Testing and Adapting REST APIs as LLM Tools|Bandlamudi et al.|2025-04-22; v3 2025-09-12|arXiv preprint|https://arxiv.org/html/2504.15546v3|Framework; data-aware testing; deployment|Direct and agent-mediated execution, builder review and error recommendations|full methods; v3 count differs from v1
draft|From Exploration to Mastery: Enabling LLMs to Master Tools via Self-Driven Interactions|Qu et al.|2024-10-10; ICLR 2025|ICLR 2025|https://proceedings.iclr.cc/paper_files/paper/2025/file/8c22e5e918198702765ecff4b20d0a90-Paper-Conference.pdf|Sections 2–3; revision appendix|Explorer/analyzer/rewriter documentation refinement|official proceedings substituted for OpenReview challenge
docschisel|DocsChisel: Adaptive Tool Documentation Optimization Framework for LLM Agents|Lu, Zhang, Chen and Peng|2026-08-10|arXiv preprint|https://arxiv.org/html/2608.10037v1|Sections III–V|Field-level trace-based repair with held-out evaluation|full methods; not independently reproduced
play2prompt|PLAY2PROMPT: Zero-shot Tool Instruction Optimization for LLM Agents via Tool Play|Fang, Zhang, Qian, Glass and Zhu|2025-03-18; ACL July 2025|Findings ACL 2025|https://aclanthology.org/2025.findings-acl.1347/|Sections 2.3–3 in linked paper|Tool play yields examples for instruction optimization|publication and paper read
easytool|EASYTOOL: Enhancing LLM-based Agents with Concise Tool Instruction|Yuan et al.|2024-01-11; NAACL 2025|NAACL 2025|https://aclanthology.org/2025.naacl-long.44/|Sections 4–5; arXiv 2401.06201|Concise descriptions, parameter guidance and verified examples|publication plus readable author methods
tracefree|Learning to Rewrite Tool Descriptions for Reliable LLM-Agent Tool Use|Guo, Dong, Gao and Das|2026-02-23|arXiv preprint|https://arxiv.org/html/2602.20426v1|Sections 3–4|Execution-derived supervision transfers to description rewriting|full methods
jtpro|JTPRO: A Joint Tool-Prompt Reflective Optimization Framework for Language Agents|Ghoshal et al.|2026-04-20|arXiv preprint|https://arxiv.org/html/2604.19821v1|Sections 3–5|Joint global-instruction and tool-description optimization|backend response correctness not the reported metric
doc2oracll|Doc2OracLL: Investigating the Impact of Documentation on LLM-Based Test Oracle Generation|Hossain, Taylor and Dwyer|2024-12-12; publication 2025-06-19|PACMSE 2(FSE), Article FSE084|https://arxiv.org/html/2412.09360v2|Sections 2–3|Documentation conditions affect generated test oracles|author full text; publisher metadata via doi:10.1145/3729354
docprompting|DocPrompting: Generating Code by Retrieving the Docs|Zhou et al.|2022-07-13; ICLR 2023|ICLR 2023|https://arxiv.org/pdf/2207.05987|Sections 2.2 and 5.2; Appendix A|Retrieve documentation to condition code generation|paper and official repository read
cloudapi|On Mitigating Code LLM Hallucinations with API Documentation|Jain et al.|2024-07-13; ICSE 2025|ICSE 2025 SEIP|https://arxiv.org/html/2407.09726|Sections 2–4|Documentation augmentation and API-call validity|signature-stub checks are not full semantic correctness
ds1000|DS-1000: A Natural and Reliable Benchmark for Data Science Code Generation|Lai et al.|2022-11-18; ICML 2023|ICML 2023, PMLR 202|https://proceedings.mlr.press/v202/lai23b.html|Sections 2.2–2.5 in linked paper|Reviewed executable library tasks and surface constraints|publication and paper read
scicode|SciCode: A Research Coding Benchmark Curated by Scientists|Tian et al.|2024-07-18|NeurIPS Datasets and Benchmarks 2024|https://arxiv.org/html/2407.13168|Section 2.3|Scientific task correctness uses domain tests and expert review|paper; venue confirmed by author repository
factory|Introducing Agent Readiness|Factory|2026-01-20|First-party product announcement|https://factory.ai/news/agent-readiness|What we measure; automated remediation|Readiness rubric, prioritized fixes and remediation PR workflow|dated vendor claim; not a controlled independent study
tessl_api|Fixing API Misuse: How Tessl Improves Agent Accuracy by up to 3.3X|Macey Baker, Tessl|2026-01-22|First-party technical report|https://tessl.io/blog/fixing-api-misuse-how-tessl-improves-agent-accuracy-by-up-to-33x|Measuring abstraction adherence|Public-library context evaluation in isolated solve/grading environments|vendor aggregate results not reproduced
tessl_skills|Introducing Task Evals: Measure Whether Your Skills Actually Work|Patrick Debois, Tessl|2026-02-17|First-party product announcement|https://tessl.io/blog/introducing-task-evals-measure-whether-your-skills-actually-work|How it works; iterate on skills|With/without-skill scenarios and iterative evaluation|dated source replaces inaccessible legacy docs page
probe_refine|Probe-and-Refine Tuning of Repository Guidance for Coding Agents|Asa Shepard and Jeannie Albrecht|2026-06-18; v2 2026-06-19|arXiv preprint|https://arxiv.org/html/2606.20512v2|Section 3.3; evaluation and limitations|Synthetic single-shot probes tune guidance before downstream issue evaluation|tuning has no executable tool loop
evaluating_agents|Evaluating AGENTS.md: Are Repository-Level Context Files Helpful for Coding Agents?|Gloaguen, Mündler, Müller, Raychev and Vechev|2026-02-12; v2 2026-06-23|arXiv preprint|https://arxiv.org/html/2602.11988v2|Sections 3–4|Context files do not generally improve success and add inference cost|v2 name CTXbench; do not reuse outdated v1 summary
agents_efficiency|On the Impact of AGENTS.md Files on the Efficiency of AI Coding Agents|Lulla et al.|2026-01-28; revised 2026-03-30|arXiv preprint|https://arxiv.org/abs/2601.20404|Section 3.1 and Table 1; v1 methods read|Paired context runs report efficiency changes|comprehensive semantic correctness explicitly outside scope
context_ablation|Do Context Files Help Coding Agents? A Two-Agent Ablation Study on Real Repositories|Prakhar Khatri|2026-07-28|arXiv preprint|https://arxiv.org/html/2607.27250v1|Sections 3–4|Repeated context ablations with hidden PR tests|small selected cohort; bounded null result
agent_readmes|Agent READMEs: An Empirical Study of Context Files for Agentic Coding|Chatlatanagulchai et al.|2025-11-17|arXiv preprint|https://arxiv.org/html/2511.12884v1|Sections 3–4|Descriptive repository instruction taxonomy|file mining does not establish treatment effectiveness
sweagent|SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering|Yang et al.|2024-05-06|NeurIPS 2024|https://arxiv.org/abs/2405.15793|Sections 2–3 and 5 in conference paper|Interface design affects coding-agent behavior|historical benchmark results
swebench|SWE-bench: Can Language Models Resolve Real-World GitHub Issues?|Jimenez et al.|2023-10-10|ICLR 2024|https://www.swebench.com/original.html|Official benchmark methods overview|Historical issue-resolution tasks and executable regression checks|official overview and conference metadata
metr|Many SWE-bench-Passing PRs Would Not Be Merged into Main|Whitfill, Wu, Becker and Rush|2026-03-10|METR research note|https://metr.org/notes/2026-03-10-many-swe-bench-passing-prs-would-not-be-merged-into-main/|Data and Methods; Reasons for Rejection|Maintainer acceptance differs from test passing|selected repositories, historical issues, no revision opportunity
retrieval|Agent Retrieval Bench: Evaluating Repository Context Retrieval for Coding Agents|Bowen Qin and Yi Xie|2026-07-27|arXiv preprint|https://arxiv.org/html/2607.24882v1|Task definitions; Section 11|Repository retrieval measured separately from patch success|file retrieval is not exact localization or resolution
evalplus|Is Your Code Generated by ChatGPT Really Correct? Rigorous Evaluation of Large Language Models for Code Generation|Jiawei Liu, Chunqiu Steven Xia, Yuyao Wang and Lingming Zhang|2023-05-02|Research paper; arXiv version cited|https://arxiv.org/html/2305.01210|Evaluation framework and results|Additional tests expose incorrect generated programs|paper read; headline gains not imported
oracle_audit|Auditing and Decomposing Feedback-Driven Evolution in LLM Test Generation under the Oracle Problem|Liang, Gan, Ying, Wei, Cui and Ni|2026-08-20|arXiv preprint|https://arxiv.org/html/2608.19626v1|Sections 2–5; limitations|Input validity and reference oracles can inflate feedback credit|paper acknowledges qualification amendments and diagnostic limitations
agentdiff|Agent-Diff: Benchmarking LLM Agents on Enterprise API Tasks via Code Execution with State-Diff-Based Evaluation|Author paper|2026-02-11|arXiv preprint|https://arxiv.org/html/2602.11224v1|Sections 5.1 and 6.3|Documentation ablation and state-diff outcome checks|methods read; complete author metadata not extracted
selfrefine|Self-Refine: Iterative Refinement with Self-Feedback|Madaan et al.|2023-03-30|Research paper; arXiv version cited|https://arxiv.org/abs/2303.17651|Abstract|Iterative generation, feedback and refinement|abstract-level background claim only
reflexion|Reflexion: Language Agents with Verbal Reinforcement Learning|Shinn, Cassano, Berman, Gopinath, Narasimhan and Yao|2023-03-20; v4 2023-10-10|NeurIPS 2023|https://arxiv.org/html/2303.11366|Framework and evaluation|Linguistic feedback is retained for later trials|primary full text accessible
textgrad|TextGrad: Automatic Differentiation via Text|Yuksekgonul, Bianchi, Boen, Liu, Huang, Guestrin and Zou|2024-06-11|arXiv version; later Nature article has different title|https://arxiv.org/abs/2406.07496|Abstract|Text feedback optimizes components of compound systems|abstract-level background; Nature open failed
gepa|GEPA: Reflective Prompt Evolution Can Outperform Reinforcement Learning|Agrawal et al.|2025-07-25; v2 2026-02-14|ICLR 2026, per author metadata|https://arxiv.org/abs/2507.19457v2|Abstract and official repository|Trajectory reflection proposes/tests prompt updates|HTML retrieval failed; narrow metadata/abstract claim
anthropic|Writing effective tools for agents — with agents|Anthropic|2025-09-11|First-party engineering article|https://www.anthropic.com/engineering/writing-tools-for-agents|Evaluation and optimization guidance|Evaluation-driven tool design with agents|engineering guidance, not peer-reviewed comparative evidence
api_learning|A field study of API learning obstacles|Martin P. Robillard and Robert DeLine|2011|Empirical Software Engineering 16, 703–732|https://www.microsoft.com/en-us/research/publication/field-study-api-learning-obstacles/|Author-host institution abstract|Human API learning obstacles include documentation and examples|year used because primary listings differ on month
api_failures|How API Documentation Fails|Gias Uddin and Martin P. Robillard|2015|IEEE Software 32(4), 68–75|https://www.cs.mcgill.ca/~martin/papers/ieeesw2015.pdf|Author publication copy|Documentation failure is an established empirical topic|limited background use; DOI 10.1109/MS.2014.80
cognitive|Using the Cognitive Dimensions Framework to evaluate the usability of a class library|Steven Clarke and Curtis Becker|2003|PPIG 15th Annual Workshop|https://www.ppig.org/papers/2003-ppig-15th-clarke/|Official abstract|API usability evaluated through cognitive dimensions|abstract-level historical background
science_lead|SWE-bench Science: Can Coding Agents Resolve Engineering Tasks in Science?|Author paper|2026-08-20|arXiv preprint; follow-up lead|https://arxiv.org/abs/2608.19799|Abstract only|Scientific repository engineering tasks|full methods not reviewed; not used for detailed novelty claims'''
records=[]
for line in RAW.splitlines():
 fields=line.split('|')
 assert len(fields)==9, line
 records.append(dict(zip(['id','title','authors','date','publication','url','evidence_location','supported_claim','access_notes'],fields),accessed='2026-09-07',confidence='high for the stated primary-source claim; no independent reproduction'))
(HERE/'source-ledger.json').write_text(json.dumps(records,indent=2,ensure_ascii=False)+'\n')
source=(HERE/'report-source.md').read_text()
refs=['\n## Annotated reading list\n','Author lists are abbreviated for reading. Dates distinguish first posting from later publication/version where verified. The follow-up lead is not counted as a full-method review.\n']
for r in records:
 refs.append(f"- **[{r['title']}]({r['url']})** — {r['authors']}. {r['date']}. {r['publication']}. {r['access_notes']}.\n")
text=source+'\n'.join(refs)
# Deliverable lives one level above the canonical internal source.
text=text.replace('../../../','../../')
(PAPER/'AIDEAL_RELATED_WORK_2026-09-07.md').write_text(text)
md=mistune.create_markdown(plugins=['table'])
body=md(text)
toc=[]
def heading(m):
 level,title=m.groups(); slug=re.sub('[^a-z0-9]+','-',re.sub('<[^>]+>','',title).lower()).strip('-')
 if level=='2':toc.append(f'<a href="#{slug}">{title}</a>')
 return f'<h{level} id="{slug}">{title}</h{level}>'
body=re.sub(r'<h([23])>(.*?)</h\1>',heading,body)
png=base64.b64encode((PAPER/'figures/AIDEAL_OVERVIEW.png').read_bytes()).decode()
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f4f7fb;color:#18253b;font:17px/1.65 system-ui,-apple-system,sans-serif}header{background:#18253b;color:white;padding:54px max(5vw,24px)}header small{color:#a6dedf;letter-spacing:.15em;font-weight:700}header h1{font-size:clamp(28px,4vw,48px);max-width:1100px;line-height:1.15}header p{max-width:1000px;color:#d3ddeb}nav{display:flex;flex-wrap:wrap;gap:9px;padding:24px 5vw;background:white;border-bottom:1px solid #dde4ef}nav a{font-size:13px;padding:5px 12px;border:1px solid #dde4ef;border-radius:18px}main{max-width:1260px;margin:36px auto;padding:0 28px 70px}article{padding:40px;background:white;border:1px solid #dde4ef;border-radius:18px}h1{line-height:1.2}article>h1{font-size:30px}h2{font-size:27px;margin-top:52px;border-top:1px solid #dde4ef;padding-top:28px;line-height:1.3}h3{font-size:21px;line-height:1.35}a{color:#176982;text-decoration:none}a:hover{text-decoration:underline}table{border-collapse:collapse;width:100%;font-size:14px;line-height:1.55;margin:24px 0}th,td{border:1px solid #dde4ef;padding:13px;vertical-align:top}th{background:#eaf1f8;text-align:left}tr:nth-child(even){background:#f8fafc}blockquote{border-left:4px solid #7050bb;background:#f4f0fb;margin:26px 0;padding:18px 24px}code{background:#eef2f7;padding:2px 5px;border-radius:4px;font-size:.9em}figure{margin:0 0 32px}figure img{width:100%;border-radius:14px;border:1px solid #dde4ef}figcaption{font-size:13px;color:#53647b;padding:10px 0}li{margin:9px 0}.tools{display:flex;gap:18px;flex-wrap:wrap;margin:15px 0 25px;font-size:14px}@media(max-width:700px){main{padding:0 12px}article{padding:20px}table{display:block;overflow:auto}nav{padding:15px}body{font-size:16px}}@media print{nav,.tools{display:none}body{background:white;font-size:10pt}main{max-width:none;padding:0;margin:0}article{border:0;padding:0}header{padding:20px;background:white;color:#18253b}header p,header small{color:#53647b}h2,h3{break-after:avoid}tr,blockquote,figure{break-inside:avoid}a{color:#18253b}table{font-size:8.5pt}}'''
page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AIDEAL — Design and related work</title><style>{css}</style></head><body><header><small>RESEARCH DOSSIER · 07 SEPTEMBER 2026</small><h1>AIDEAL: evidence, prior work and the paper's contribution</h1><p>An editable architecture figure, a preserved design memo, and a primary-source review separating established ideas from contributions still to demonstrate.</p></header><nav aria-label="Report sections">{''.join(toc)}</nav><main><figure><img src="data:image/png;base64,{png}" alt="AIDEAL overview: human scope definition; frozen configuration, API manifest, fixtures and harness; LLM-assisted A1 A2 B1 B2 tests; deterministic evidence assessment; and a human-reviewed improvement process. Teal marks deterministic automation, purple LLM calls, amber human decisions and blue operator agents."><figcaption>Architecture overview. Arrows show logical dependencies, not simultaneous job execution. The LLM cells include deterministic execution. B1 uses original+aideal documentation; B2 uses aideal documentation. The separate improvement queue records review and does not launch an executor.</figcaption></figure><div class="tools"><a href="figures/AIDEAL_OVERVIEW.svg">Editable SVG</a><a href="figures/AIDEAL_OVERVIEW.pdf">Vector PDF</a><a href="AIDEAL_EXPLANATION_VERBATIM_2026-09-07.md">Verbatim explanation memo</a><a href="../../AIDEAL_CODE_GUIDE.md">Detailed code guide</a><a href="AIDEAL_RELATED_WORK_2026-09-07.md">Markdown report</a></div><article>{body}</article></main></body></html>'''
(PAPER/'AIDEAL_RELATED_WORK_2026-09-07.html').write_text(page)
print(f'Rendered dossier with {len(records)} source records, including one abstract-only follow-up lead.')
